"""init

Revision ID: cbba5d89b3ac
Revises:
Create Date: 2024-12-11 10:34:50.845505

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbba5d89b3ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gender_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gender_name"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("teleg_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("birthday", sa.String(), nullable=False),
        sa.Column("about", sa.String(length=500), nullable=False),
        sa.Column("gender", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gender"],
            ["genders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("teleg_id"),
    )
    op.create_table(
        "ban_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("banned_user_id", sa.Integer(), nullable=False),
        sa.Column("ban_status", sa.Integer(), nullable=False),
        sa.Column("date_of_ban", sa.String(), nullable=False),
        sa.Column("comment_to_ban", sa.String(length=500), nullable=False),
        sa.Column("date_of_unban", sa.String(), nullable=False),
        sa.Column("comment_to_unban", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["banned_user_id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "holidays_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("till_date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "met_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_user_id", sa.Integer(), nullable=False),
        sa.Column("second_user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_user_id"],
            ["user_info.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_user_id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tg_usernames",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_mets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("met_info", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mets_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("met_id", sa.Integer(), nullable=False),
        sa.Column("who_id", sa.Integer(), nullable=False),
        sa.Column("about_whom_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("date_of_comment", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["about_whom_id"],
            ["user_info.id"],
        ),
        sa.ForeignKeyConstraint(
            ["met_id"],
            ["met_info.id"],
        ),
        sa.ForeignKeyConstraint(
            ["who_id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mets_reviews")
    op.drop_table("user_status")
    op.drop_table("user_mets")
    op.drop_table("tg_usernames")
    op.drop_table("met_info")
    op.drop_table("holidays_status")
    op.drop_table("ban_list")
    op.drop_table("user_info")
    op.drop_table("genders")
    # ### end Alembic commands ###
